name = "example_01_simple"
version = "0.1.0"
target = "javascript"

[dependencies]
lustre = "~> 5.0"

[dev-dependencies]
lustre_dev_tools = "~> 2.0"

[tools.lustre.html]
title = "Simple Lustre Example"
stylesheets = [{ href = "/styles.css" }]
